image: docker:24.0
services:
  - docker:24.0-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  WORKDIR: /home/$PROJECT_USER/$CI_PROJECT_NAME
  DEVDIR: $WORKDIR-dev

stages:
  - (dev) build_and_deploy
  - pre-prod
  - build_and_push
  - deploy

before_script:
  - set -o errexit -o pipefail
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - ssh-add <(echo $SSH_PRIVATE_KEY | base64 -d)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - echo $KUBECONFIG_PROD | base64 -d > kubeconfig.yaml
  - chmod 600 kubeconfig.yaml
